def generate_design_md(result: dict) -> str:
    dna = result.get("dna", {})
    colors = result.get("colors", {})
    typography = result.get("typography", {})
    layout = result.get("layout", {})
    components = result.get("components", [])
    patterns = result.get("patterns", [])

    lines = []
    lines.append(f"# Design Analysis: {result.get('title', result.get('url', ''))}")
    lines.append("")
    lines.append(f"- **URL**: {result.get('url', '')}")
    lines.append(f"- **Style**: {dna.get('style', 'N/A')} ({dna.get('style_confidence', 0)}% confidence)")
    lines.append(f"- **Complexity**: {dna.get('complexity', 'N/A')}")
    lines.append(f"- **Visual Score**: {dna.get('visual_score', 'N/A')}")
    lines.append(f"- **Accessibility**: {dna.get('accessibility', 'N/A')}")
    lines.append("")

    palette = colors.get("palette", {})
    lines.append("## Color Palette")
    lines.append("")
    for name, hex_val in palette.items():
        if hex_val:
            lines.append(f"- **{name.replace('_', ' ').title()}**: `{hex_val}`")
    lines.append("")
    lines.append(f"Total unique colors detected: {colors.get('count', 0)}")
    lines.append("")

    lines.append("## Typography")
    lines.append("")
    if typography.get("primary_font"):
        lines.append(f"- Primary font: **{typography['primary_font']}**")
    if typography.get("secondary_font"):
        lines.append(f"- Secondary font: **{typography['secondary_font']}**")
    lines.append(f"- Font families used: {', '.join(typography.get('families', []) or ['N/A'])}")
    lines.append("")

    lines.append("## Layout")
    lines.append("")
    lines.append(f"- Responsive: {'Yes' if layout.get('responsive') else 'No'}")
    lines.append(f"- CSS Grid: {'Yes' if layout.get('uses_grid') else 'No'}")
    lines.append(f"- Flexbox: {'Yes' if layout.get('uses_flexbox') else 'No'}")
    if layout.get("max_container_width"):
        lines.append(f"- Max container width: {layout['max_container_width']}px")
    if layout.get("container_widths"):
        widths = ", ".join(str(w) for w in layout["container_widths"][:5])
        lines.append(f"- Container widths: {widths}px")
    lines.append("")

    valid_comps = [c for c in components if isinstance(c, dict)]
    if valid_comps:
        lines.append("## Components Detected")
        lines.append("")
        for c in valid_comps:
            conf = c.get("confidence", 0)
            name = c.get("type", "unknown")
            selector = c.get("selector", "")
            bar = "█" * (conf // 10) + "░" * (10 - conf // 10)
            lines.append(f"- **{name.title()}** {bar} {conf}% `{selector}`")
        lines.append("")

    if patterns:
        lines.append("## UX Patterns")
        lines.append("")
        for p in patterns:
            check = "✓" if p.get("confidence", 0) > 60 else "○"
            lines.append(f"- {check} **{p['name']}** — {p.get('description', '')}")
        lines.append("")

    summary = dna.get("summary", "")
    if summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by DesignOracle*")

    return "\n".join(lines)
