def generate_react_components(result: dict) -> str:
    components = result.get("components", [])
    colors = result.get("colors", {}).get("palette", {})
    typography = result.get("typography", {})
    dna = result.get("dna", {})
    patterns = result.get("patterns", [])

    lines = []
    lines.append("// Auto-generated components from DesignOracle")
    lines.append("// Style: " + dna.get("style", "Unknown"))
    lines.append("")
    lines.append("const style = {")
    if colors.get("primary"):
        lines.append(f"  '--color-primary': '{colors['primary']}',")
    if colors.get("accent"):
        lines.append(f"  '--color-accent': '{colors['accent']}',")
    if typography.get("primary_font"):
        lines.append(f"  '--font-sans': '{typography['primary_font']}',")
    lines.append("};")
    lines.append("")

    comp_types = {c.get("type") for c in components if isinstance(c, dict)}

    if "navbar" in comp_types or any("navbar" in str(p.get("name", "")).lower() for p in patterns):
        lines.append("export function Navbar() {")
        lines.append("  return (")
        lines.append("    <nav style={{")
        lines.append("      display: 'flex', alignItems: 'center', justifyContent: 'space-between',")
        lines.append("      padding: '16px 24px', borderBottom: '1px solid #e5e7eb',")
        lines.append("      position: 'sticky', top: 0, background: '#fff', zIndex: 50")
        lines.append("    }}>")
        lines.append("      <div style={{ fontWeight: 700, fontSize: 18 }}>Logo</div>")
        lines.append("      <div style={{ display: 'flex', gap: 24 }}>")
        lines.append("        <a href='#'>Features</a>")
        lines.append("        <a href='#'>Pricing</a>")
        lines.append("        <a href='#'>About</a>")
        lines.append("      </div>")
        lines.append("    </nav>")
        lines.append("  );")
        lines.append("}")
        lines.append("")

    if "hero" in comp_types:
        lines.append("export function Hero() {")
        lines.append("  return (")
        lines.append("    <section style={{")
        lines.append("      padding: '80px 24px', textAlign: 'center',")
        lines.append("      maxWidth: 720, margin: '0 auto'")
        lines.append("    }}>")
        lines.append("      <h1 style={{")
        lines.append("        fontSize: 48, fontWeight: 800, letterSpacing: '-0.02em',")
        lines.append("        marginBottom: 16, lineHeight: 1.1")
        lines.append("      }}>")
        lines.append("        Build something amazing")
        lines.append("      </h1>")
        lines.append("      <p style={{")
        lines.append("        fontSize: 18, color: '#6b7280', lineHeight: 1.6, marginBottom: 32")
        lines.append("      }}>")
        lines.append("        A powerful platform to create, deploy, and scale your ideas.")
        lines.append("      </p>")
        lines.append("      <button style={{")
        lines.append("        padding: '12px 28px', fontSize: 16, fontWeight: 600,")
        lines.append("        background: `var(--color-primary, #6366f1)`, color: '#fff',")
        lines.append("        border: 'none', borderRadius: 8, cursor: 'pointer'")
        lines.append("      }}>")
        lines.append("        Get Started")
        lines.append("      </button>")
        lines.append("    </section>")
        lines.append("  );")
        lines.append("}")
        lines.append("")

    if "features" in comp_types:
        lines.append("export function Features() {")
        lines.append("  return (")
        lines.append("    <section style={{")
        lines.append("      padding: '80px 24px', display: 'grid',")
        lines.append("      gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',")
        lines.append("      gap: 24, maxWidth: 1100, margin: '0 auto'")
        lines.append("    }}>")
        lines.append("      {['Fast', 'Reliable', 'Scalable'].map(title => (")
        lines.append("        <div key={title} style={{")
        lines.append("          padding: 24, borderRadius: 12, border: '1px solid #e5e7eb',")
        lines.append("          background: '#f9fafb'")
        lines.append("        }}>")
        lines.append("          <h3 style={{ fontWeight: 600, marginBottom: 8 }}>{title}</h3>")
        lines.append("          <p style={{ color: '#6b7280', lineHeight: 1.5 }}>")
        lines.append("            Description of this amazing feature.")
        lines.append("          </p>")
        lines.append("        </div>")
        lines.append("      ))}")
        lines.append("    </section>")
        lines.append("  );")
        lines.append("}")
        lines.append("")

    if "pricing" in comp_types:
        lines.append("export function Pricing() {")
        lines.append("  return (")
        lines.append("    <section style={{")
        lines.append("      padding: '80px 24px', display: 'grid',")
        lines.append("      gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',")
        lines.append("      gap: 20, maxWidth: 900, margin: '0 auto', textAlign: 'center'")
        lines.append("    }}>")
        lines.append("      {['Starter', 'Pro', 'Enterprise'].map(plan => (")
        lines.append("        <div key={plan} style={{")
        lines.append("          padding: 32, borderRadius: 12, border: '1px solid #e5e7eb',")
        lines.append("          background: plan === 'Pro' ? '#f0f0ff' : '#f9fafb'")
        lines.append("        }}>")
        lines.append("          <h3 style={{ fontSize: 20, fontWeight: 700 }}>{plan}</h3>")
        lines.append("          <div style={{ fontSize: 36, fontWeight: 800, margin: '16px 0' }}>$29</div>")
        lines.append("          <button style={{")
        lines.append("            padding: '10px 24px', background: `var(--color-primary, #6366f1)`,")
        lines.append("            color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer'")
        lines.append("          }}>Choose Plan</button>")
        lines.append("        </div>")
        lines.append("      ))}")
        lines.append("    </section>")
        lines.append("  );")
        lines.append("}")
        lines.append("")

    if "footer" in comp_types:
        lines.append("export function Footer() {")
        lines.append("  return (")
        lines.append("    <footer style={{")
        lines.append("      padding: '48px 24px 24px', borderTop: '1px solid #e5e7eb',")
        lines.append("      display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 32,")
        lines.append("      maxWidth: 1100, margin: '0 auto'")
        lines.append("    }}>")
        lines.append("      <div>")
        lines.append("        <div style={{ fontWeight: 700, marginBottom: 12 }}>Company</div>")
        lines.append("        <div style={{ color: '#6b7280', fontSize: 14 }}>© 2026</div>")
        lines.append("      </div>")
        lines.append("      <div>")
        lines.append("        <div style={{ fontWeight: 600, marginBottom: 8 }}>Product</div>")
        lines.append("        <div style={{ display: 'flex', flexDirection: 'column', gap: 4, color: '#6b7280', fontSize: 14 }}>")
        lines.append("          <a href='#'>Features</a>")
        lines.append("          <a href='#'>Pricing</a>")
        lines.append("        </div>")
        lines.append("      </div>")
        lines.append("      <div>")
        lines.append("        <div style={{ fontWeight: 600, marginBottom: 8 }}>Legal</div>")
        lines.append("        <div style={{ color: '#6b7280', fontSize: 14 }}>Privacy · Terms</div>")
        lines.append("      </div>")
        lines.append("    </footer>")
        lines.append("  );")
        lines.append("}")
        lines.append("")

    lines.append("export { style };")
    return "\n".join(lines)
